name: Week's Historical Celestial Forecast

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow once a day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate-forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script to generate the JSON
      run: |
        python week’s_celestial_forecast.py

    - name: Add newly created files to tracking
      run: |
        git add weeks_historical_celestial_forecast.json

    - name: Commit and push the updated JSON file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "Update Week's Historical Celestial Forecast JSON file"
        git push origin main
